# -*- coding: utf-8 -*-
"""real_world_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReNknJjZoCNBMhcfCwo-5T28dsGELgpk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url="https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv"

df=pd.read_csv(url)


print(df.head())
print(df.shape)
print(df.columns)
print(df.info())

df = df.rename(columns={
    "lifeExp": "life_expectancy",
    "pop": "population",
    "gdpPercap": "gdp_per_capita"
})

print(df.head())
print(df.columns)

print("Missing values in each column:")
print(df.isna().sum)

print("Number of duplicate rows:", df.duplicated().sum())

df_clean = df.copy()

# Remove exact duplicate rows if any
if df_clean.duplicated().sum() > 0:
    df_clean = df_clean.drop_duplicates()

# Strip extra spaces from text columns
for col in ["country", "continent"]:
    df_clean[col] = df_clean[col].astype(str).str.strip()

# Ensure expected data types
df_clean["year"] = df_clean["year"].astype(int)
df_clean["population"] = df_clean["population"].astype(float)
df_clean["life_expectancy"] = df_clean["life_expectancy"].astype(float)
df_clean["gdp_per_capita"] = df_clean["gdp_per_capita"].astype(float)

print(df_clean.dtypes)
print(df_clean.head())

# dirty_demo = df_clean.head(12).copy()

# # Deliberately introduce missing values for teaching practice
# dirty_demo.loc[2, "life_expectancy"] = np.nan
# dirty_demo.loc[5, "gdp_per_capita"] = np.nan

# print(dirty_demo)
# print(dirty_demo.isna().sum())

# # Fill missing numerical values using median
# clean_demo = dirty_demo.copy()
# clean_demo["life_expectancy"] = clean_demo["life_expectancy"].fillna(clean_demo["life_expectancy"].median())
# clean_demo["gdp_per_capita"] = clean_demo["gdp_per_capita"].fillna(clean_demo["gdp_per_capita"].median())

# print(clean_demo.isna().sum())
# print(clean_demo)

num_of_country=df["country"].nunique()
print("Number of countries:", num_of_country)
num_of_cont=df["continent"].nunique()
print("Number of continents:", num_of_cont)

latest_year=df["year"].max()
latest_data=df[df["year"]==latest_year].copy()
latest_data

# plt.plot(df["continent"],df["life_expectancy"])
# plt.show()
# Latest year ke data me continent-wise average life expectancy
continent_life = latest_data.groupby("continent")["life_expectancy"].mean()

plt.figure(figsize=(8, 5))
plt.bar(continent_life.index, continent_life.values)

plt.title(f"Average Life Expectancy by Continent in {latest_year}")
plt.xlabel("Continent")
plt.ylabel("Average Life Expectancy")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# plt.plot(df["life_expectancy"],df["year"])
# plt.show()
selected_countries = ["India", "China", "United States"]
trend_df = df_clean[df_clean["country"].isin(selected_countries)]

plt.figure(figsize=(9, 5))

for country in selected_countries:
    country_df = trend_df[trend_df["country"] == country]
    plt.plot(country_df["year"],
             country_df["life_expectancy"],
             marker="o",
             label=country)

plt.title("Life Expectancy Trend Over Time")
plt.xlabel("Year")
plt.ylabel("Life Expectancy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

continent_gdp_per_capita = latest_data.groupby('continent')['gdp_per_capita'].mean().reset_index()
display(continent_gdp_per_capita)

top_5_gdp_countries = latest_data.sort_values(by='gdp_per_capita', ascending=False).head(5)
display(top_5_gdp_countries)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x='continent', y='gdp_per_capita', data=continent_gdp_per_capita, palette='viridis', hue='continent', legend=False)
plt.title(f'Average GDP per Capita by Continent in {latest_year}')
plt.xlabel('Continent')
plt.ylabel('Average GDP per Capita')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 7))
sns.boxplot(x='continent', y='gdp_per_capita', data=latest_data, palette='coolwarm', hue='continent', legend=False)
plt.title(f'Distribution of GDP per Capita by Continent in {latest_year}')
plt.xlabel('Continent')
plt.ylabel('GDP per Capita')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.linear_model import LinearRegression

# Prepare the data
X = df_clean['gdp_per_capita'].values.reshape(-1, 1) # Independent variable (features)
y = df_clean['life_expectancy'].values # Dependent variable (target)

# Create and fit the model
model = LinearRegression()
model.fit(X, y)

# Get the coefficients
slope = model.coef_[0]
intercept = model.intercept_

print(f"Regression Equation: Life Expectancy = {slope:.4f} * GDP per Capita + {intercept:.2f}")
print(f"Coefficient (Slope): {slope:.4f}")
print(f"Intercept: {intercept:.2f}")

import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x='gdp_per_capita', y='life_expectancy', data=df_clean, alpha=0.6)

# Plot the regression line
plt.plot(X, model.predict(X), color='red', linewidth=2, label='Regression Line')

plt.title('Linear Regression: Life Expectancy vs. GDP per Capita')
plt.xlabel('GDP per Capita')
plt.ylabel('Life Expectancy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Get the list of top 5 wealthiest countries
top_5_countries_list = top_5_gdp_countries['country'].tolist()

# Calculate average life expectancy for top 5 countries in the latest year
life_exp_top_5 = latest_data[latest_data['country'].isin(top_5_countries_list)]['life_expectancy'].mean()

# Calculate average life expectancy for the rest of the world in the latest year
life_exp_rest_of_world = latest_data[~latest_data['country'].isin(top_5_countries_list)]['life_expectancy'].mean()

print(f"Average Life Expectancy for Top 5 Wealthiest Countries (in {latest_year}): {life_exp_top_5:.2f}")
print(f"Average Life Expectancy for the Rest of the World (in {latest_year}): {life_exp_rest_of_world:.2f}")

comparison_data = pd.DataFrame({
    'Category': ['Top 5 Wealthiest Countries', 'Rest of the World'],
    'Average Life Expectancy': [life_exp_top_5, life_exp_rest_of_world]
})

plt.figure(figsize=(9, 6))
sns.barplot(x='Category', y='Average Life Expectancy', data=comparison_data, palette='viridis', hue='Category', legend=False)
plt.title(f'Average Life Expectancy Comparison in {latest_year}')
plt.xlabel('Category')
plt.ylabel('Average Life Expectancy')
plt.ylim(0, max(life_exp_top_5, life_exp_rest_of_world) * 1.1)
plt.tight_layout()
plt.show()

def calculate_life_expectancy_gap_for_year(data_frame, year_val):
    # Filter data for the current year
    year_data = data_frame[data_frame['year'] == year_val].copy()

    if year_data.empty:
        return None

    # Identify top 5 wealthiest countries for the current year
    top_5_gdp_countries_year = year_data.sort_values(by='gdp_per_capita', ascending=False).head(5)
    top_5_countries_list_year = top_5_gdp_countries_year['country'].tolist()

    # Calculate average life expectancy for top 5 countries
    life_exp_top_5_year = year_data[year_data['country'].isin(top_5_countries_list_year)]['life_expectancy'].mean()

    # Calculate average life expectancy for the rest of the world
    life_exp_rest_of_world_year = year_data[~year_data['country'].isin(top_5_countries_list_year)]['life_expectancy'].mean()

    # Calculate the gap
    gap = life_exp_top_5_year - life_exp_rest_of_world_year

    return gap

# Get all unique years from the cleaned DataFrame
all_years = sorted(df_clean['year'].unique())

# List to store results
gap_data = []

# Calculate gap for each year
for year in all_years:
    gap = calculate_life_expectancy_gap_for_year(df_clean, year)
    if gap is not None:
        gap_data.append({'year': year, 'life_expectancy_gap': gap})

# Create a DataFrame from the results
gap_df = pd.DataFrame(gap_data)

display(gap_df.head())

plt.figure(figsize=(12, 7))
sns.lineplot(x='year', y='life_expectancy_gap', data=gap_df, marker='o')
plt.title('Life Expectancy Gap (Top 5 Wealthiest vs. Rest) Over Time')
plt.xlabel('Year')
plt.ylabel('Life Expectancy Gap (Years)')
plt.grid(True)
plt.tight_layout()
plt.show()

# Predict life expectancy using the trained model for all data
df_clean['predicted_life_expectancy'] = model.predict(df_clean['gdp_per_capita'].values.reshape(-1, 1))

# Calculate the difference (residual) between actual and predicted life expectancy
df_clean['life_expectancy_residual'] = df_clean['life_expectancy'] - df_clean['predicted_life_expectancy']

# Filter for the latest year to focus on the most recent trend
latest_data_with_residuals = df_clean[df_clean['year'] == latest_year].copy()

# Sort by residual to find the top outperformers (positive residuals)
outperformers = latest_data_with_residuals.sort_values(by='life_expectancy_residual', ascending=False).head(10)

display(outperformers[['country', 'gdp_per_capita', 'life_expectancy', 'predicted_life_expectancy', 'life_expectancy_residual']])

plt.figure(figsize=(12, 8))
sns.scatterplot(x='gdp_per_capita', y='life_expectancy', data=latest_data_with_residuals, alpha=0.6, label='All Countries')

# Plot the regression line
plt.plot(latest_data_with_residuals['gdp_per_capita'], latest_data_with_residuals['predicted_life_expectancy'], color='red', linewidth=2, label='Regression Line')

# Highlight outperformers
sns.scatterplot(x='gdp_per_capita', y='life_expectancy', data=outperformers, color='green', s=100, label='Top Outperformers', zorder=5)

# Annotate the outperformers
for i, row in outperformers.iterrows():
    plt.text(row['gdp_per_capita'], row['life_expectancy'] + 0.5, row['country'], fontsize=9, ha='center', va='bottom')

plt.title(f'Countries Outperforming Wealth-Expectancy Trend in {latest_year}')
plt.xlabel('GDP per Capita')
plt.ylabel('Life Expectancy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df_clean['life_expectancy_residual'], kde=True, bins=30)
plt.title('Distribution of Life Expectancy Residuals (Actual - Predicted)')
plt.xlabel('Life Expectancy Residual (Years)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()